<?php

namespace Database\Seeders;

use App\Models\Faq;
use App\Models\Page;
use Illuminate\Database\Seeder;

/**
 * Starter CMS content in English and French. Legal pages are templates that must be
 * reviewed by a lawyer in each target market before launch (section 12).
 */
class ContentSeeder extends Seeder
{
    private const LEGAL_NOTE_EN = "> Template text. This page must be reviewed by a qualified lawyer for each target market before launch.\n\n";

    private const LEGAL_NOTE_FR = "> Texte modèle. Cette page doit être relue par un juriste qualifié pour chaque marché avant la mise en ligne.\n\n";

    public function run(): void
    {
        foreach ($this->pages() as $slug => $locales) {
            foreach ($locales as $locale => [$title, $summary, $body]) {
                Page::query()->firstOrCreate(['slug' => $slug, 'locale' => $locale], [
                    'title' => $title,
                    'summary' => $summary,
                    'body' => $body,
                    'is_published' => true,
                    'published_at' => now()->subDay(),
                ]);
            }
        }

        if (Faq::query()->exists()) {
            return;
        }

        foreach ($this->faqs() as $locale => $items) {
            foreach ($items as $index => [$category, $question, $answer]) {
                Faq::query()->create(['locale' => $locale, 'category' => $category, 'question' => $question, 'answer' => $answer, 'sort_order' => $index, 'is_published' => true]);
            }
        }
    }

    /**
     * @return array<string, array<string, array{0: string, 1: string, 2: string}>>
     */
    private function pages(): array
    {
        $brand = config('platform.brand.name');

        return [
            'customs' => [
                'en' => ['Customs guide', 'Duties, documents and what to declare for international shipments.', <<<MD
## What you must declare
Every international shipment needs an accurate description of its contents, their value and the reason for export (gift, sale, personal effects). Customs authorities can open any parcel.

## Duties and taxes
Import duties and taxes are set by the destination country and are usually paid by the recipient. They depend on the type of goods, their value and their origin.

| Destination | Typical threshold before duties | Notes |
| --- | --- | --- |
| European Union | No VAT threshold, duties from 150 EUR | VAT is due on almost every import |
| United States | 800 USD (de minimis) | Some goods are always controlled |
| Cameroon | Depends on category | Personal effects can be exempt |

## Documents
- Commercial invoice (generated by {$brand} once your payment is approved)
- Copy of the sender's and recipient's ID for high-value shipments
- Permits or certificates for restricted goods (medicine, electronics with batteries)

## Restricted and prohibited items
Check our [prohibited items list](/prohibited-items) before booking. False declarations can lead to seizure and fines.
MD],
                'fr' => ['Guide des douanes', 'Droits, documents et déclarations pour les envois internationaux.', <<<MD
## Ce que vous devez déclarer
Chaque envoi international nécessite une description exacte du contenu, sa valeur et le motif d'export (cadeau, vente, effets personnels). Les douanes peuvent ouvrir tout colis.

## Droits et taxes
Les droits et taxes d'importation sont fixés par le pays de destination et sont en général payés par le destinataire. Ils dépendent de la nature, de la valeur et de l'origine des biens.

| Destination | Seuil habituel avant droits | Remarques |
| --- | --- | --- |
| Union européenne | Pas de seuil de TVA, droits dès 150 EUR | La TVA est due sur presque toutes les importations |
| États-Unis | 800 USD (de minimis) | Certains biens sont toujours contrôlés |
| Cameroun | Selon la catégorie | Les effets personnels peuvent être exonérés |

## Documents
- Facture commerciale (générée par {$brand} une fois votre paiement validé)
- Copie des pièces d'identité de l'expéditeur et du destinataire pour les envois de valeur
- Permis ou certificats pour les biens réglementés (médicaments, électronique avec batteries)

## Articles réglementés et interdits
Consultez notre [liste des articles interdits](/fr/articles-interdits) avant de réserver. Une fausse déclaration peut entraîner une saisie et des amendes.
MD],
            ],
            'packing' => [
                'en' => ['Packing guide', 'How to pack and label your parcels so they arrive safely.', <<<'MD'
## Choose the right box
Use a rigid, double-wall cardboard box with room for 5 cm of cushioning on every side. Reused boxes are fine if they are not damaged and old labels are removed.

## Protect the contents
1. Wrap each item separately.
2. Fill empty space with bubble wrap, paper or foam so nothing moves when you shake the box.
3. Put liquids in sealed bags, upright, with absorbent material.

## Close and label
- Seal with 5 cm wide packing tape using the H method.
- Stick the label on the largest side, flat and fully visible.
- Remove or cover old barcodes.

## Weight and size
We price on the larger of actual and volumetric weight: length × width × height (cm) ÷ 5000. A light but bulky box costs more than its weight suggests, so use the smallest box that fits.
MD],
                'fr' => ["Guide d'emballage", 'Comment emballer et étiqueter vos colis pour qu’ils arrivent intacts.', <<<'MD'
## Choisir le bon carton
Utilisez un carton rigide à double cannelure laissant 5 cm de calage de chaque côté. Un carton réutilisé convient s'il est en bon état et sans anciennes étiquettes.

## Protéger le contenu
1. Emballez chaque objet séparément.
2. Comblez les vides avec du papier bulle, du papier ou de la mousse.
3. Placez les liquides dans des sacs étanches, debout, avec un absorbant.

## Fermer et étiqueter
- Fermez avec un ruban adhésif de 5 cm en H.
- Collez l'étiquette sur la plus grande face, bien à plat et visible.
- Retirez ou masquez les anciens codes-barres.

## Poids et dimensions
Nous facturons le plus élevé du poids réel et du poids volumétrique : longueur × largeur × hauteur (cm) ÷ 5000. Utilisez le plus petit carton possible.
MD],
            ],
            'about' => [
                'en' => ['About us', "{$brand} connects Africa, Europe and North America by air, sea and road.", "## Our mission\n{$brand} makes international shipping simple and transparent for families and businesses: one quote, one booking, one tracking number from pickup to delivery.\n\n## How we work\nWe operate our own consolidated air, sea and road lanes between our hubs, then hand over to established local networks for the last mile: USPS and UPS in the United States, FedEx in Europe, and our partners elsewhere.\n\n## Why customers choose us\n- Instant, published prices\n- Payments checked by real people before anything is released\n- Support in English and French\n\n> Company details (legal entity, registration and address) will be completed when confirmed."],
                'fr' => ['À propos', "{$brand} relie l'Afrique, l'Europe et l'Amérique du Nord par air, mer et route.", "## Notre mission\n{$brand} rend l'expédition internationale simple et transparente pour les familles et les entreprises : un devis, une réservation, un numéro de suivi de l'enlèvement à la livraison.\n\n## Notre fonctionnement\nNous exploitons nos propres lignes groupées aériennes, maritimes et routières entre nos hubs, puis confions le dernier kilomètre à des réseaux locaux reconnus : USPS et UPS aux États-Unis, FedEx en Europe et nos partenaires ailleurs.\n\n## Pourquoi nous choisir\n- Des prix publiés et immédiats\n- Des paiements vérifiés par de vraies personnes avant toute libération\n- Une assistance en français et en anglais\n\n> Les informations légales (société, immatriculation, adresse) seront complétées dès confirmation."],
            ],
            'terms' => [
                'en' => ['Terms of service', 'The rules that apply when you use our website and services.', self::LEGAL_NOTE_EN."## 1. Scope\nThese terms apply to quotes, bookings, payments and tracking on this website.\n\n## 2. Quotes and prices\nQuotes are indicative and valid for 7 days. The price is fixed at booking. If the measured weight or size differs from the declaration, the difference is invoiced or refunded.\n\n## 3. Your obligations\nYou must describe contents accurately, pack them properly and never ship prohibited items. You are responsible for the contents of your shipment.\n\n## 4. Payment\nOrders are paid using the methods shown on your order. Your label and tracking number are released only after our team approves your payment. Unpaid orders expire after 48 hours.\n\n## 5. Liability\nOur liability for loss or damage is limited to the declared value when insurance is purchased, and otherwise to the limits set out in the shipping policy.\n\n## 6. Cancellations\nYou may cancel before pickup. Refunds follow the refund policy.\n\n## 7. Governing law\nTo be completed for each market."],
                'fr' => ["Conditions d'utilisation", "Les règles applicables à l'utilisation du site et de nos services.", self::LEGAL_NOTE_FR."## 1. Champ d'application\nCes conditions s'appliquent aux devis, réservations, paiements et au suivi sur ce site.\n\n## 2. Devis et prix\nLes devis sont indicatifs et valables 7 jours. Le prix est figé à la réservation. Si le poids ou les dimensions mesurés diffèrent, l'écart est facturé ou remboursé.\n\n## 3. Vos obligations\nVous devez décrire le contenu avec exactitude, l'emballer correctement et ne jamais expédier d'articles interdits.\n\n## 4. Paiement\nLes commandes se règlent avec les moyens affichés sur votre commande. Votre étiquette et votre numéro de suivi sont libérés après validation du paiement par notre équipe. Les commandes impayées expirent après 48 heures.\n\n## 5. Responsabilité\nNotre responsabilité est limitée à la valeur déclarée en cas d'assurance, et sinon aux limites de la politique d'expédition.\n\n## 6. Annulation\nVous pouvez annuler avant l'enlèvement. Les remboursements suivent la politique de remboursement.\n\n## 7. Droit applicable\nÀ compléter pour chaque marché."],
            ],
            'privacy' => [
                'en' => ['Privacy policy', 'How we collect, use and protect your personal data.', self::LEGAL_NOTE_EN."## Data we collect\nAccount details (name, email, phone), addresses, shipment contents, payment proofs and technical logs.\n\n## Why we use it\nTo price, book and deliver shipments, verify payments, prevent fraud, comply with customs and legal obligations, and answer your requests.\n\n## Legal basis\nPerformance of the contract, legal obligations, and our legitimate interest in preventing fraud. Optional cookies need your consent.\n\n## Retention\nPayment proofs: 24 months. Logs: 12 months. Audit records: 5 years. Invoices: as required by law.\n\n## Your rights\nYou can access, correct, export and ask to delete your data from your account or by writing to ".config('platform.brand.data_contact').".\n\n## Security\nProofs and documents are stored privately and shown only through short-lived links to you and authorised staff. Sensitive fields are encrypted."],
                'fr' => ['Politique de confidentialité', 'Comment nous collectons, utilisons et protégeons vos données.', self::LEGAL_NOTE_FR."## Données collectées\nInformations de compte (nom, e-mail, téléphone), adresses, contenu des envois, preuves de paiement et journaux techniques.\n\n## Finalités\nTarifer, réserver et livrer les envois, vérifier les paiements, prévenir la fraude, respecter les obligations douanières et légales, et répondre à vos demandes.\n\n## Base légale\nExécution du contrat, obligations légales et intérêt légitime de prévention de la fraude. Les cookies non essentiels nécessitent votre consentement.\n\n## Conservation\nPreuves de paiement : 24 mois. Journaux : 12 mois. Journal d'audit : 5 ans. Factures : selon la loi.\n\n## Vos droits\nAccès, rectification, export et suppression depuis votre compte ou en écrivant à ".config('platform.brand.data_contact').".\n\n## Sécurité\nLes preuves et documents sont stockés de façon privée et accessibles uniquement par des liens temporaires. Les champs sensibles sont chiffrés."],
            ],
            'cookies' => [
                'en' => ['Cookie policy', 'The cookies we use and why.', self::LEGAL_NOTE_EN."## Essential cookies\n- **Session** cookie: keeps you signed in and protects forms against forgery (CSRF).\n- **XSRF-TOKEN**: security token for requests from this site.\n- **device_id**: recognises your device to warn you about sign-ins from new devices.\n\nThese cookies are required and do not need consent.\n\n## Analytics\nWe do not use advertising or analytics cookies, and we do not send personal data to analytics providers."],
                'fr' => ['Politique cookies', 'Les cookies que nous utilisons et pourquoi.', self::LEGAL_NOTE_FR."## Cookies essentiels\n- Cookie de **session** : maintient votre connexion et protège les formulaires (CSRF).\n- **XSRF-TOKEN** : jeton de sécurité pour les requêtes du site.\n- **device_id** : reconnaît votre appareil pour vous alerter d'une connexion depuis un nouvel appareil.\n\nCes cookies sont nécessaires et ne requièrent pas de consentement.\n\n## Mesure d'audience\nNous n'utilisons ni cookies publicitaires ni cookies de mesure d'audience."],
            ],
            'shipping-policy' => [
                'en' => ['Shipping and liability policy', 'Transit times, responsibilities and limits of liability.', self::LEGAL_NOTE_EN."## Transit times\nTransit times are estimates. Customs, weather and carrier events can cause delays.\n\n## Responsibility for contents\nThe sender is responsible for the contents, their declaration and their packing.\n\n## Liability\nWithout insurance, liability for loss or damage is limited per kilogram according to applicable international conventions. With insurance, cover is up to the declared value.\n\n## Delivery\nThe last mile in the United States is handled by USPS or UPS and in Europe by FedEx. Their delivery conditions apply to that leg."],
                'fr' => ["Politique d'expédition et de responsabilité", 'Délais, responsabilités et limites.', self::LEGAL_NOTE_FR."## Délais\nLes délais sont des estimations. La douane, la météo et les transporteurs peuvent causer des retards.\n\n## Responsabilité du contenu\nL'expéditeur est responsable du contenu, de sa déclaration et de son emballage.\n\n## Responsabilité\nSans assurance, la responsabilité est limitée par kilogramme selon les conventions internationales applicables. Avec assurance, jusqu'à la valeur déclarée.\n\n## Livraison\nLe dernier kilomètre est assuré par USPS ou UPS aux États-Unis et par FedEx en Europe. Leurs conditions s'appliquent à cette étape."],
            ],
            'claims-policy' => [
                'en' => ['Claims procedure', 'How to report a lost, damaged or delayed shipment.', self::LEGAL_NOTE_EN."## Time limits\n- Damage: within 7 days of delivery\n- Loss: within 30 days of the expected delivery date\n\n## How to claim\nOpen a claim from your account (Claims page), describe what happened and upload photos of the parcel, packaging and contents.\n\n## What happens next\nWe review the evidence, may ask for more information, and send our decision by email. Approved claims are paid to the original payer."],
                'fr' => ['Procédure de réclamation', 'Signaler un envoi perdu, endommagé ou en retard.', self::LEGAL_NOTE_FR."## Délais\n- Dommage : dans les 7 jours suivant la livraison\n- Perte : dans les 30 jours suivant la date prévue\n\n## Comment réclamer\nOuvrez une réclamation depuis votre compte, décrivez les faits et joignez des photos du colis, de l'emballage et du contenu.\n\n## Ensuite\nNous examinons les éléments, pouvons demander des précisions et vous informons par e-mail. Les indemnisations sont versées au payeur d'origine."],
            ],
            'prohibited-items' => [
                'en' => ['Prohibited and restricted items', 'Goods we cannot carry, and goods that need special handling.', "## Prohibited\nCash and negotiable instruments, weapons and ammunition, explosives and fireworks, narcotics, perishable food, live animals, counterfeit goods, hazardous chemicals.\n\n## Restricted\n- **Medicine**: only with a prescription and in personal quantities\n- **Lithium batteries**: only installed in devices, never loose\n- **Electronics**: declare brand, model and value\n\nBookings with prohibited categories are blocked automatically. Undeclared prohibited items are handed to the authorities."],
                'fr' => ['Articles interdits et réglementés', 'Les biens que nous ne transportons pas et ceux soumis à conditions.', "## Interdits\nEspèces et titres négociables, armes et munitions, explosifs et feux d'artifice, stupéfiants, denrées périssables, animaux vivants, contrefaçons, produits chimiques dangereux.\n\n## Réglementés\n- **Médicaments** : sur ordonnance et en quantité personnelle\n- **Batteries lithium** : uniquement installées dans un appareil\n- **Électronique** : déclarer marque, modèle et valeur\n\nLes réservations avec des catégories interdites sont bloquées automatiquement."],
            ],
            'refund-policy' => [
                'en' => ['Refund policy', 'When and how refunds are made.', self::LEGAL_NOTE_EN."## Before pickup\nIf you cancel a paid order before pickup, we refund the amount paid, minus non-recoverable payment fees.\n\n## After pickup\nShipping charges are not refundable once the shipment is in transit, except under an approved claim.\n\n## How refunds are paid\nRefunds are recorded by our team and paid back to the original payer, using the original method where possible. Gift cards are non-refundable once redeemed."],
                'fr' => ['Politique de remboursement', 'Quand et comment nous remboursons.', self::LEGAL_NOTE_FR."## Avant l'enlèvement\nEn cas d'annulation d'une commande payée avant l'enlèvement, nous remboursons le montant payé, hors frais de paiement non récupérables.\n\n## Après l'enlèvement\nLes frais d'expédition ne sont pas remboursables une fois l'envoi en transit, sauf réclamation acceptée.\n\n## Modalités\nLes remboursements sont enregistrés par notre équipe et versés au payeur d'origine, si possible par le même moyen. Les cartes cadeaux ne sont pas remboursables une fois utilisées."],
            ],
            'payment-terms' => [
                'en' => ['Payment terms', 'How manual payments, proofs and verification work.', self::LEGAL_NOTE_EN."## How to pay\nChoose a payment method on your order. Account details are shown only to you, after you choose. Send the exact amount and write your payment reference in the note.\n\n## Proof and verification\nUpload a screenshot or receipt. A payment verifier checks the amount, date, payer and reference, and may confirm in our account statement. Orders above a set amount need two verifiers.\n\n## Release\nYour label, tracking number and invoice are released only after approval.\n\n## Gift cards\nWhere offered, gift cards are accepted as payment for shipping services only and are non-refundable once redeemed. Never buy gift cards because someone else asked you to pay for a parcel.\n\n## Fraud\nForged or altered proofs are refused and may be reported."],
                'fr' => ['Conditions de paiement', 'Fonctionnement des paiements manuels, des preuves et de la vérification.', self::LEGAL_NOTE_FR."## Payer\nChoisissez un moyen de paiement sur votre commande. Les coordonnées s'affichent uniquement pour vous, après ce choix. Envoyez le montant exact avec votre référence dans le motif.\n\n## Preuve et vérification\nEnvoyez une capture ou un reçu. Un vérificateur contrôle le montant, la date, le payeur et la référence. Au-delà d'un certain montant, deux vérificateurs sont nécessaires.\n\n## Libération\nVotre étiquette, votre numéro de suivi et votre facture sont libérés uniquement après validation.\n\n## Cartes cadeaux\nLorsqu'elles sont proposées, elles sont acceptées uniquement pour nos services et ne sont pas remboursables une fois utilisées. N'achetez jamais de cartes cadeaux à la demande d'un tiers.\n\n## Fraude\nLes preuves falsifiées sont refusées et peuvent être signalées."],
            ],
        ];
    }

    /**
     * @return array<string, array<int, array{0: string, 1: string, 2: string}>>
     */
    private function faqs(): array
    {
        return [
            'en' => [
                ['tracking', 'When do I get my tracking number?', 'As soon as our team approves your payment. You receive it by email and it appears in your account with your label.'],
                ['tracking', 'Can I track USPS, UPS and FedEx parcels here?', 'Yes. Paste the number in the tracking box: we recognise the carrier from the format. Live carrier data appears once our tracking provider is connected; otherwise we link to the carrier site.'],
                ['tracking', 'Why does my number say "not found"?', 'Check for typos. New shipments appear only after payment approval. If the problem continues, contact us with your order number.'],
                ['payments', 'Which payment methods do you accept?', 'The methods enabled for your order appear on the payment page. Account details are shown only after you choose a method, on your own order.'],
                ['payments', 'How long does payment verification take?', 'Our target is 30 minutes during staffed hours. You receive an email as soon as it is done.'],
                ['payments', 'What should my proof of payment show?', 'The amount, the date, the recipient and your payment reference. A screenshot of the confirmation screen or a PDF receipt works best.'],
                ['payments', 'Someone asked me to pay for a parcel. Is it safe?', 'Only pay for shipments you booked yourself. If a seller, a contact or a "customs officer" asks you to pay a fee or buy gift cards, it may be a scam. Contact us first.'],
                ['shipping', 'How is the price calculated?', 'From the origin and destination zones, the chargeable weight (the larger of actual and volumetric weight) and the transport mode, plus fuel and handling surcharges and optional insurance.'],
                ['shipping', 'Can I ship by road to another continent?', 'No. Road freight is offered only when origin and destination are on the same landmass. The quote tool suggests air or sea instead.'],
                ['customs', 'Who pays import duties?', 'Usually the recipient, according to the rules of the destination country. See the customs guide for details.'],
                ['account', 'How do I turn on two-factor authentication?', 'Go to Profile and security in your account and follow the steps with an authenticator app.'],
                ['account', 'How do I delete my account?', 'Use the deletion request in Profile and security. We confirm by email within 30 days.'],
            ],
            'fr' => [
                ['tracking', 'Quand vais-je recevoir mon numéro de suivi ?', 'Dès que notre équipe valide votre paiement. Vous le recevez par e-mail et il apparaît dans votre compte avec votre étiquette.'],
                ['tracking', 'Puis-je suivre des colis USPS, UPS et FedEx ici ?', 'Oui. Collez le numéro dans la zone de suivi : nous reconnaissons le transporteur. Les données en direct apparaissent une fois notre fournisseur connecté ; sinon nous renvoyons vers le site du transporteur.'],
                ['tracking', 'Pourquoi mon numéro est-il « introuvable » ?', 'Vérifiez la saisie. Les nouveaux envois apparaissent seulement après validation du paiement. Sinon, contactez-nous avec votre numéro de commande.'],
                ['payments', 'Quels moyens de paiement acceptez-vous ?', 'Les moyens activés pour votre commande s’affichent sur la page de paiement. Les coordonnées ne sont visibles qu’après votre choix, sur votre propre commande.'],
                ['payments', 'Combien de temps dure la vérification du paiement ?', 'Notre objectif est de 30 minutes pendant les heures d’ouverture. Vous recevez un e-mail dès qu’elle est terminée.'],
                ['payments', 'Que doit montrer ma preuve de paiement ?', 'Le montant, la date, le bénéficiaire et votre référence de paiement. Une capture de l’écran de confirmation ou un reçu PDF conviennent le mieux.'],
                ['payments', 'Quelqu’un me demande de payer un colis. Est-ce sûr ?', 'Ne payez que les envois que vous avez réservés vous-même. Si un vendeur, un contact ou un « douanier » vous demande des frais ou des cartes cadeaux, il peut s’agir d’une arnaque. Contactez-nous d’abord.'],
                ['shipping', 'Comment le prix est-il calculé ?', 'Selon les zones de départ et d’arrivée, le poids taxable (le plus élevé du poids réel et volumétrique) et le mode de transport, plus les surcharges carburant et manutention et l’assurance optionnelle.'],
                ['shipping', 'Puis-je envoyer par la route vers un autre continent ?', 'Non. Le transport routier n’est proposé que si le départ et l’arrivée sont sur le même continent. L’outil de devis propose alors l’aérien ou le maritime.'],
                ['customs', 'Qui paie les droits de douane ?', 'En général le destinataire, selon les règles du pays de destination. Consultez le guide des douanes.'],
                ['account', 'Comment activer la double authentification ?', 'Allez dans Profil et sécurité et suivez les étapes avec une application d’authentification.'],
                ['account', 'Comment supprimer mon compte ?', 'Utilisez la demande de suppression dans Profil et sécurité. Nous confirmons par e-mail sous 30 jours.'],
            ],
        ];
    }
}
