<?php

namespace App\Services\Notifications;

use App\Services\Content\MarkdownRenderer;

/**
 * Renders admin-editable templates. Variable values are escaped for Markdown, so a customer
 * name cannot inject links or formatting; only *_url variables generated by the app are trusted.
 */
class TemplateRenderer
{
    public function __construct(private readonly MarkdownRenderer $markdown) {}

    /**
     * @param  array<string, scalar|null>  $variables
     * @return array{subject: string, html: string, text: string}
     */
    public function render(string $subject, string $body, array $variables): array
    {
        $renderedSubject = $this->replace($subject, $variables, false);
        $renderedBody = $this->replace($body, $variables, true);

        return [
            'subject' => trim(preg_replace('/[\r\n]+/', ' ', $renderedSubject) ?? ''),
            'html' => $this->markdown->toHtml($renderedBody),
            'text' => $this->replace($body, $variables, false),
        ];
    }

    /**
     * @param  array<string, scalar|null>  $variables
     */
    private function replace(string $template, array $variables, bool $forMarkdown): string
    {
        return (string) preg_replace_callback('/\{\{\s*([a-z0-9_]+)\s*\}\}/i', function (array $match) use ($variables, $forMarkdown): string {
            $key = $match[1];
            if (! array_key_exists($key, $variables)) {
                return '';
            }

            $value = (string) $variables[$key];

            if (! $forMarkdown || str_ends_with($key, '_url')) {
                return $value;
            }

            return $this->escapeMarkdown($value);
        }, $template);
    }

    private function escapeMarkdown(string $value): string
    {
        $value = str_replace(["\r", "\n"], ' ', $value);

        return (string) preg_replace('/([\\\\`*_{}\[\]()#+\-.!<>|~])/', '\\\\$1', $value);
    }
}
